import { ChangeEvent, KeyboardEvent, useEffect, useRef, useState } from 'react';

type Decision = { symbol?: string; direction?: string; confidence?: number; entry?: number; stop_loss?: number; take_profits?: number[]; expected_rr?: number; reason?: string; entry_status?: string };
type Message = { id: string; role: 'user' | 'assistant'; content: string; image?: string; decision?: Decision; streaming?: boolean };
type Conversation = { id: string; title: string; active_symbol?: string | null; updated_at: string };
const prompts = ['Analyze BTCUSDT across multiple timeframes', 'Build a risk-managed ETHUSDT swing trade plan', 'Compare SOLUSDT and ETHUSDT momentum', 'Show my paper trading performance'];

function App() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [conversationId, setConversationId] = useState<string>();
  const [draft, setDraft] = useState(''); const [image, setImage] = useState<string>();
  const [streaming, setStreaming] = useState(false); const [error, setError] = useState<string | null>(null);
  const [sidebarOpen, setSidebarOpen] = useState(false); const aborter = useRef<AbortController | null>(null); const fileInput = useRef<HTMLInputElement>(null); const end = useRef<HTMLDivElement>(null);
  useEffect(() => { void loadConversations(); }, []);
  useEffect(() => { end.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, streaming]);

  async function loadConversations() { try { const response = await fetch('/api/conversations'); if (response.ok) setConversations(await response.json()); } catch { setError('The conversation service is unavailable.'); } }
  async function createConversation() { const response = await fetch('/api/conversations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: 'New conversation' }) }); if (!response.ok) throw new Error('Unable to create a conversation.'); const created = await response.json() as Conversation; setConversations(items => [created, ...items]); setConversationId(created.id); setMessages([]); return created.id; }
  async function selectConversation(id: string) {
    try {
      const response = await fetch(`/api/conversations/${id}`);
      if (!response.ok) throw new Error('Unable to load conversation.');
      const data = await response.json() as { messages: Array<{ id: string; role: 'user' | 'assistant'; content: string }> };
      setConversationId(id); setMessages(data.messages.map(item => ({ ...item }))); setSidebarOpen(false);
    } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load conversation.'); }
  }
  function stopReply() { aborter.current?.abort(); setStreaming(false); setMessages(items => items.map(item => item.streaming ? { ...item, streaming: false } : item)); }
  async function sendMessage(value = draft) {
    const question = value.trim(); if (!question || streaming) return;
    setDraft(''); setImage(undefined); setError(null); setStreaming(true);
    const user: Message = { id: crypto.randomUUID(), role: 'user', content: question, image }; const assistantId = crypto.randomUUID();
    setMessages(items => [...items, user, { id: assistantId, role: 'assistant', content: '', streaming: true }]);
    try {
      const id = conversationId || await createConversation(); const controller = new AbortController(); aborter.current = controller;
      const response = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'text/event-stream' }, body: JSON.stringify({ conversation_id: id, message: question }), signal: controller.signal });
      if (!response.ok || !response.body) throw new Error('Chat service did not return a stream.');
      const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = '';
      while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const blocks = buffer.split('\n\n'); buffer = blocks.pop() || ''; blocks.forEach(block => consumeEvent(block, assistantId)); }
      setMessages(items => items.map(item => item.id === assistantId ? { ...item, streaming: false, content: item.content || 'No response was returned.' } : item)); await loadConversations();
    } catch (err) { if ((err as Error).name !== 'AbortError') { setError(err instanceof Error ? err.message : 'Unable to reach chat service.'); setMessages(items => items.map(item => item.id === assistantId ? { ...item, streaming: false, content: 'Unable to complete this request.' } : item)); } }
    finally { setStreaming(false); aborter.current = null; }
  }
  function consumeEvent(block: string, assistantId: string) { const type = block.match(/^event: (.+)$/m)?.[1]; const raw = block.match(/^data: (.+)$/m)?.[1]; if (!raw) return; try { const data = JSON.parse(raw) as { text?: string; decision?: Decision; reason?: string }; setMessages(items => items.map(item => item.id !== assistantId ? item : type === 'partial_text' ? { ...item, content: data.text || item.content } : type === 'analysis_result' && data.decision ? { ...item, decision: data.decision } : type === 'analysis_result' && data.reason ? { ...item, content: item.content || `Decision: NO_TRADE. ${data.reason}` } : item)); } catch { /* Ignore malformed SSE frames without losing the stream. */ } }
  function keyDown(event: KeyboardEvent<HTMLTextAreaElement>) { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void sendMessage(); } }
  function pickImage(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file?.type.startsWith('image/')) setImage(URL.createObjectURL(file)); event.target.value = ''; }
  return <div className="workspace"><aside className={`sidebar ${sidebarOpen ? 'open' : ''}`} aria-label="Chat history"><div className="sidebar-brand"><span className="brand-orb">△</span><span>Orion</span><small>TRADING AI</small></div><button className="new-chat" onClick={() => void createConversation()}><span>＋</span> New chat</button><nav className="chat-nav"><p>RECENT</p>{conversations.map(chat => <button key={chat.id} className={chat.id === conversationId ? 'active' : ''} onClick={() => void selectConversation(chat.id)}>{chat.title}</button>)}</nav><div className="sidebar-footer"><span>Paper-only market intelligence</span></div></aside>{sidebarOpen && <button className="scrim" aria-label="Close navigation" onClick={() => setSidebarOpen(false)} />}<main className="conversation"><header className="workspace-header"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setSidebarOpen(true)}>☰</button><div className="header-title"><strong>Trading workspace</strong><span><i /> Persistent chat and live market context</span></div></header><section className={`message-scroll ${messages.length ? 'has-messages' : ''}`} aria-live="polite">{messages.length === 0 ? <EmptyWorkspace onPrompt={setDraft} /> : messages.map(message => <MessageBubble key={message.id} message={message} />)}{error && <p className="inline-error">{error}</p>}<div ref={end} /></section><Composer draft={draft} image={image} streaming={streaming} onChange={setDraft} onKeyDown={keyDown} onSend={() => void sendMessage()} onStop={stopReply} onAttach={() => fileInput.current?.click()} onRemoveImage={() => setImage(undefined)} /><input ref={fileInput} className="visually-hidden" type="file" accept="image/*" onChange={pickImage} /></main></div>;
}
function EmptyWorkspace({ onPrompt }: { onPrompt: (value: string) => void }) { return <div className="empty-workspace"><div className="hero-mark">⌁</div><p className="eyebrow">CONVERSATIONAL MARKET INTELLIGENCE</p><h1>See the market<br /><em>before it moves.</em></h1><p className="hero-copy">Ask for a thesis, a setup, or a risk-defined paper trade plan.</p><div className="prompt-grid">{prompts.map(prompt => <button key={prompt} onClick={() => onPrompt(prompt)}><span>{prompt}</span><b>↗</b></button>)}</div></div>; }
function MessageBubble({ message }: { message: Message }) { return <article className={`message ${message.role}`}><div className="avatar">{message.role === 'user' ? 'YOU' : '△'}</div><div className="message-body"><div className="message-label">{message.role === 'user' ? 'YOU' : 'ORION'} {message.streaming && <span className="typing">thinking</span>}</div>{message.image && <img className="message-image" src={message.image} alt="Attached market chart" />}<p>{message.content || ' '}{message.streaming && <span className="cursor" />}</p>{message.decision && <AnalysisCard decision={message.decision} />}</div></article>; }
function AnalysisCard({ decision }: { decision: Decision }) { return <section className="analysis-card"><div className="card-top"><div><span>DETERMINISTIC PAPER DECISION</span><h2>{decision.symbol || 'MARKET'} <small>{decision.entry_status || 'WAIT'}</small></h2></div><div className="confidence"><b>{Math.round((decision.confidence || 0) * 100)}%</b><span>CONFIDENCE</span></div></div><div className="direction"><span>Directional bias</span><strong>{decision.direction || 'NO_TRADE'}</strong><small>{decision.reason}</small></div>{decision.entry !== undefined && <div className="levels"><div><span>ENTRY</span><b>{decision.entry}</b></div><div><span>STOP LOSS</span><b className="danger">{decision.stop_loss}</b></div><div><span>TP1 / RR</span><b className="profit">{decision.take_profits?.[0]} / {decision.expected_rr}</b></div></div>}</section>; }
function Composer({ draft, image, streaming, onChange, onKeyDown, onSend, onStop, onAttach, onRemoveImage }: { draft: string; image?: string; streaming: boolean; onChange: (value: string) => void; onKeyDown: (event: KeyboardEvent<HTMLTextAreaElement>) => void; onSend: () => void; onStop: () => void; onAttach: () => void; onRemoveImage: () => void }) { return <div className="composer-wrap">{image && <div className="image-preview"><img src={image} alt="Attachment preview" /><button onClick={onRemoveImage} aria-label="Remove attachment">×</button></div>}<div className="composer"><button className="attach-button" onClick={onAttach} aria-label="Attach chart image">＋</button><textarea value={draft} rows={1} placeholder="Ask Orion about the market…" onChange={event => onChange(event.target.value)} onKeyDown={onKeyDown} aria-label="Message Orion" />{streaming ? <button className="stop-button" onClick={onStop} aria-label="Stop generating"><span /></button> : <button className="send-button" onClick={onSend} disabled={!draft.trim()} aria-label="Send message">↑</button>}</div><p className="composer-hint">Enter to send <span>·</span> Shift + Enter for new line</p></div>; }
export default App;
